Fix #3061
horovod/horovod pull request #3066
Opened 2021-07-30 00:58 UTC by barry-jin

## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs?
- [ ] Did you write any tests to validate this change?  
- [ ] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

Fixes #3061.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

2021-07-30 07:50 UTC, EnricoMi commented
@barry-jin thanks for looking into this. These tests run against various MXNet version, all the way back to 1.5.1.

So either the tests are written in a way they work with all versions, or those modified tests are cloned to a mxnet 2.0 version which runs mutually exclusive (skipIf).

2021-07-30 16:29 UTC, barry-jin commented
> @barry-jin thanks for looking into this. These tests run against various MXNet version, all the way back to 1.5.1.
> 
> So either the tests are written in a way they work with all versions, or those modified tests are cloned to a mxnet 2.0 version which runs mutually exclusive (skipIf).

@EnricoMi I see. Because there are a lot of breaking changes in MXNet2.0, especially for Gluon API and array objects. I'm wondering if we can create a new test file (test_mxnet2.py) for MXNet2.0 tests.

2021-08-01 09:19 UTC, EnricoMi requested changes

2021-08-01 09:19 UTC, EnricoMi commented on test/parallel/test_mxnet2.py
> +class MXTests(unittest.TestCase):
Can we call this `MX2Tests` and derive it from `MXTests` so we don't copy all that code and have to maintain it in two places? Then `MX2Tests` can override and reimplement those tests that don't work in MXNet 2.0 only.

Will be interesting how the `@pytest.mark.skipif` handles the class hierarchy.

2021-08-03 11:25 UTC, EnricoMi commented
@barry-jin thanks for the MXNet 2 fixes. I have reworked the `test_mxnet.py` in #3071, which includes your contribution. We can finish this fix there or you merge it into your branch and we finish it here. Either way, your contribution should be acknowledge when we merge my branch into master.

2021-08-03 15:31 UTC, barry-jin commented
@EnricoMi Thanks! Let's finish the fix in #3072

2021-08-03 17:27 UTC, closed without merging