Move the estimator out of the train function so that Ray can pickle t…
horovod/horovod pull request #3122
Opened 2021-08-20 18:10 UTC by porterrf

…he train function.  Create the intermediate directory

## Checklist before submitting

- [x] Did you read the [contributor guide](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md)?
- [n/a] Did you update the docs?
- [local tests] Did you write any tests to validate this change?  
- [n/a] Did you update the [CHANGELOG](https://github.com/horovod/horovod/blob/master/CHANGELOG.md), if this change affects users?

## Description

[#3114](https://github.com/horovod/horovod/commit/b64166d2d0127fbc17d834b2d589c457ecc1d6f9) introduced a bug when running spark/Lightning on Ray.  This change moves estimator out of the train function to fix that bug.  Additionally, we create the logs dir so that the profiler can write to it.

## Review process to land 

1. All tests and other checks must succeed.
2. At least one member of the [technical steering committee](https://github.com/horovod/horovod/blob/master/CONTRIBUTING.md) must review and approve.
3. If any member of the technical steering committee requests changes, they must be addressed.

2021-08-20 18:59 UTC, chongxiaoc approved these changes

2021-08-20 19:00 UTC, chongxiaoc requested changes
Can you format your git commit msg?

2021-08-21 02:44 UTC, chongxiaoc approved these changes

2021-08-21 02:46 UTC, chongxiaoc commented
@EnricoMi  Is `test_spark_task_service_abort_command` a flaky test? I think this change is not related to that.

2021-08-21 03:47 UTC, porterrf commented
I'm debugging an issue where rank >0 is failing to write the profile.  Moved this one back to draft.

2021-08-30 21:49 UTC, merged